import { NextSessionProvider } from "@/components/auth/next-auth-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { AuthModal } from "@/components/auth/auth-modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "dark flex  items-center justify-center"
        )}
      >
        <NextSessionProvider>
          {children}
          <AuthModal />
        </NextSessionProvider>
      </body>
    </html>
  );
}
